export default {
  extends: ['stylelint-config-standard'],
  ignoreFiles: ['dist/**', 'node_modules/**'],
  rules: {
    'custom-property-pattern': null,
    'keyframes-name-pattern': null,
    'selector-class-pattern': null,
    'declaration-empty-line-before': null,
    'color-function-notation': 'modern',
    'alpha-value-notation': 'number',
    'no-descending-specificity': null,
    'at-rule-no-unknown': [true, { ignoreAtRules: ['theme', 'layer', 'property', 'tailwind'] }],
    'import-notation': null,
    'value-keyword-case': null,
    'custom-property-empty-line-before': null,
    'rule-empty-line-before': null,
    'comment-empty-line-before': null,
    'at-rule-empty-line-before': null,
    'declaration-block-single-line-max-declarations': null,
    'shorthand-property-no-redundant-values': null,
    'media-feature-range-notation': null,
    'no-duplicate-selectors': null,
  },
};
